### ISSUE TITLE
Jira cloud/Harness Drone integration problems

### ISSUE THREAD

**Issue by jherrera13** [drone/drone-jira#2]
Creating public issue as suggested by Peter Hack from Harness, for the Jira cloud/Harness Drone integration problems
- **Updatesequencenumber** to be a monotonically increasing int64, like epoch milliseconds (or seconds would be fine).
- **JiraPipeline** to use the pipeline name for id, instead of email.
- **Log the response from POST to Jira**, even on HTTP 202. I think there are messages in there that customers need to see (certainly in support scenarios).

**Comment by tphoney** [comment]
Hey @jherrera13 i have made some of your suggested changes, and the reasoning for my changes.
- Updatesequencenumber  is set to use the build number from drone, and this makes sense. As it is a int64
- JiraPipeline now uses the pipeline name
- Log the response from POST to Jira, typically plugins are not meant to display loads of information, if a user wants to see the post response from jira they can set this variable. `log_level` eg

```yaml
- name: jira publish
  image: plugins/jira
  settings:
    client_id:
      from_secret: jira_client_id
    client_secret:
      from_secret: jira_client_secret
    instance: droneio
    project: TT
    environment_name: staging
    log_level: DEBUG
    pipeline: bash_plugin
```
