### ISSUE TITLE
Add PLUGIN_ISSUE_KEYS to Accept Arrays of Issue Keys

### ISSUE THREAD

**Issue by Ompragash** [drone/drone-jira#21]
## Description:
This enhancement request proposes adding a new plugin configuration option PLUGIN_ISSUE_KEYS that allows passing multiple issue keys as an array. If this parameter is not provided, the current behavior of extracting the issue key from the commit message will remain unchanged.

## Problem:
Currently, the plugin only supports extracting a single issue key from the commit message, pull request title, branch name, etc. In cases where multiple issue keys are associated with a single deployment or build, this limitation prevents users from explicitly providing those issue keys in the plugin configuration.

## Solution:
Introduce a new parameter PLUGIN_ISSUE_KEYS to accept an array of issue keys. The plugin will prioritize this parameter if provided. If it is not provided, the plugin will continue with the current extraction behavior from the commit details.

## Example Usage:
1.	Passing Multiple Issue Keys:
Users can now pass multiple issue keys using the PLUGIN_ISSUE_KEYS parameter:
```yaml
- name: deployment
  image: plugins/jira
  settings:
    cloud_id: your-cloud-id
    client_id: your-client-id
    client_secret: your-client-secret
    project: SCRUM
    issue_keys:
      - SCRUM-1
      - SCRUM-2
      - SCRUM-3
      - SCRUM-4
```
2.	Old Behavior (No Issue Keys Passed):
If PLUGIN_ISSUE_KEYS is not provided, the plugin will default to the existing behavior of extracting a single issue key from the commit message or other sources.
